services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: symfony_app
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
    networks:
      - symfony_network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    mem_limit: 2g
    container_name: symfony_php
    restart: always
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
    networks:
      - symfony_network
    environment:
      JWT_PASSPHRASE: your_secret_pass
    command: >
      bash -c "mkdir -p config/jwt && 
               if [ ! -f config/jwt/private.pem ]; then 
                 openssl genpkey -algorithm RSA -out config/jwt/private.pem -aes256 -pass pass:$JWT_PASSPHRASE && 
                 openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem -passin pass:$JWT_PASSPHRASE; 
               fi && 
               php-fpm"

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
