services:
    _defaults:
        autowire: true      # Автоматичне впровадження залежностей
        autoconfigure: true # Автоматичне налаштування для команд, підписників подій і т. д.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Зареєструй контролер як публічний сервіс з тегом для Symfony
    App\Controller\RegistrationController:
        tags: ['controller.service_arguments']
    App\Controller\AuthController:
        tags: ['controller.service_arguments']